### ISSUE TITLE
Remove duplicate types and class types when detecting changes in class declarations and class type declarations. 

### ISSUE THREAD

**Issue by azzsal** [ocaml-semver/ocaml-api-watch#104]
As noted by #90 and #103, when adding a class declaration an object type and a class type are added by the compiler beside the class itself, and when adding a class type, an object type is added beside the class type. The same is true when removing or modifying a class or a class type. 

For example, if cls1 has been added to a module signature: 

```ocaml

class cls1 : object
  method m1 : int -> int
end
```

they will get this: 

```
 +type cls1 = < m1 : int -> int >
 +class cls1 : object method m1 : int -> int end
 +class type cls1 = object method m1 : int -> int end
```
whereby they expect just a class declaration is added:

```
 +class cls1 : object method m1 : int -> int end
```

I think a possible approach would be to check a field in the type_declaration, class_declaration or a class_type_declaration record before adding it to the Sig_item_map that we build at the start of the diffing process.

The tests should be updated accordingly as well.

**Comment by azzsal** [comment]
@NathanReb Please assign this to me.

**Comment by NathanReb** [comment]
Sure, just did! Indeed I think not adding those items in the first place is probably the way to go indeed.

Let me know if you need any help with this and don't hesitate to open a draft PR if you need guidance!
