### ISSUE TITLE
Add github actions to keep changelog up to date

### ISSUE THREAD

**Issue by NathanReb** [ocaml-semver/ocaml-api-watch#77]
Since we released the first prototype to opam, we now have to maintain our changelog.

To ensure it is kept up to date as we go, we should add a github action that checks it's been properly updated for incoming PRs.

We can reuse the same setup that is used in [ocaml-ppx/ppxlib](https://github.com/ocaml-ppx/ppxlib) for instance. You can see the github actions that are defined [here](https://github.com/ocaml-ppx/ppxlib/blob/main/.github/workflows/changelog.yml) and [here](https://github.com/ocaml-ppx/ppxlib/blob/main/.github/workflows/pr-number.yml).

There are two actions we'd like to use here:
- The first checks every PR and fails if the changelog file has not been updated. The check is disables is the PR is labeled with the `no changelog` label.
- The second helps writing changelog entries by replacing `<PR_NUMBER>` with the actual PR number once the PR is opened. This allows contributors to add `(#<PR_NUMBER>, @username)` at the end of their changelog entry before opening the pull request.

**Comment by Nancyenos** [comment]
I am an outreachy intern could this issue be assigned to me

**Comment by panglesd** [comment]
Hello @Nancyenos !

While this issue does not need you to know OCaml, we still ask you to be able to build the project before assigning you an issue! See my post in #78 for more information!

**Comment by RitaAkor** [comment]
Hello, could this issue be assigned to me, please?

Thank you!
<img width="1280" alt="Screenshot 2024-10-03 at 23 58 48" src="https://github.com/user-attachments/assets/5f03445e-bb01-49f1-a09c-2d10c9ab97a3">

**Comment by panglesd** [comment]
Hello @RitaAkor,

Since you have already an issue assigned, and likely completed (I need to review), we are likely to propose you a more advanced issue, and keep "good first issues" to newcomers. We'll get back to you soon!
