### ISSUE TITLE
Detect addition and removal of module types

### ISSUE THREAD

**Issue by NathanReb** [ocaml-semver/ocaml-api-watch#81]
The current implementation of our API diffing does not handle every type of item that can be defined within a module.

It will compare items that we support, detecting addition, removal and modification of said items. If it fails to detect any such change, it will default back to comparing the whole module using `Includemod.signatures`.

Our ultimate goal is to support fine grained diffing of each and every signature items.

To get one step closer, we would like to add detection of the addition and removal of modtype_declaration items.

## How to proceed

The diffing logic and representation is found in [`lib/diff.ml`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/lib/diff.ml).

The content of a module is represented as a list even though the order does not matter there. To work around that we first build a map of its content, indexed by pairs of item type and name. We then proceed to compare the two maps we built from the two versions of the module we are diffing. If both map contain a mapping for a given type/name pair, we compare them to try and detect whether it was modified. If only one of the map contains a binding for a given pair, that means that it was either added or removed, based on which map has the binding.

To detect addition/removal of module type declarations, we will have to extend the [`item_type`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/lib/diff.ml#L23) and [`sig_items`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/lib/diff.ml#L24) types which are used to build the map mentioned above. These are then used in the [`extract_items`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/lib/diff.ml#L30) function that builds the map from the module signature.

Finally, the actual diffing logic's entry point is the [`Diff.items`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/lib/diff.ml#L79) function which handles the comparison of the two maps via the merge function (you can read the documentation [here](https://ocaml.org/manual/5.2/api/Map.S.html#VALmerge)).

## Testing

This should be tested at the library level. You can add a new `tests/api-watch/test_diff_modtype_decl.ml` file where you can write tests for type addition or removal. You can use the [`tests/api-watch/test_diff.ml`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/tests/api-watch/test_diff.ml) or [`tests/api-watch/test_diff_module.ml`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/tests/api-watch/test_diff_module.ml) files as examples on how to write such tests.

**Comment by NchamJosephMuam** [comment]
here is my man page:

![image](https://github.com/user-attachments/assets/1d0cbe5d-af90-4108-916d-529a212dd079)

**Comment by panglesd** [comment]
Hello @NchamJosephMuam !

Yes, let this issue be assigned to you!
