### ISSUE TITLE
Split the monolithic cram test into multiple files

### ISSUE THREAD

**Issue by panglesd** [ocaml-semver/ocaml-api-watch#85]
The [`tests/api-diff/run.t`](https://github.com/ocaml-semver/ocaml-api-watch/blob/main/tests/api-diff/run.t) file contains tests for the `api-diff` tool, "end to end": that is, checking that some input to the tool produces the expected final output.

The tests are written using [`dune`'s support from cram tests.](https://dune.readthedocs.io/en/stable/tests.html#cram-tests)

However, almost all cram tests are in a single file. This makes it harder to read, and won't scale when we add more tests.

It would be better to group tests by features, in separate files with a relevant name.

**Comment by Dezzy12** [comment]
Hello,

I am an Outreachy applicant. Could this issue please be assigned to me?

**Comment by panglesd** [comment]
Yes, sure! It's assigned to you!
