### ISSUE TITLE
Abstract away Sig_item_map

### ISSUE THREAD

**Issue by NathanReb** [ocaml-semver/ocaml-api-watch#96]
Our Sig_item_map module is growing and its current implementation and API are not the best as they allow incorrect combination of keys and bindings.

We would like to extract it to its own module and improve its API so that the user (us) does not have to deal with those impossible cases.

To keep things simple we'll likely need a GADT (you can read more about them in the [OCaml manual](https://ocaml.org/manual/5.2/gadts-tutorial.html) or [RealWorldOCaml](https://dev.realworldocaml.org/gadts.html)).

I propose the following API:
```ocaml
type t

type _ item_type =
  | Value : value_declaration item_type
  | Module : module_declaration item_type
  ...

val empty : t

val add : name: string -> 'a item_type -> 'a -> t -> t

val diff : diff_item: ('a item_type -> 'a option -> 'a option -> 'diff option) -> t -> t -> 'diff list
```

The simplest and most straightforward implementation would be to build one internal map per item_type as suggested by @panglesd.

**Comment by azzsal** [comment]
I'd like to work on this.

**Comment by NathanReb** [comment]
There you go!
